name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        NODE_OPTIONS: --max-old-space-size=4096
        
    - name: Verify build artifacts
      run: |
        echo "✅ Build completed successfully!"
        echo "📦 Build artifacts created:"
        ls -la dist/
        echo "📊 Build size:"
        du -sh dist/
        
    - name: Comment PR with build status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `✅ **Build Successful!**
            
            🎉 Your CritterChat application has been built successfully!
            
            📦 **Build Details:**
            - ✅ Dependencies installed
            - ✅ TypeScript/JavaScript compiled
            - ✅ Assets optimized
            - ✅ Production build ready
            
            🚀 The application is ready for deployment when Vercel secrets are configured.`
          });
